pool:
  name: Azure Pipelines
  demands: npm

steps:
- task: Npm@1
  displayName: 'install angular cli'
  inputs:
    workingDir: '$(Build.SourcesDirectory)'
    verbose: false

- task: Npm@1
  displayName: 'build angular app'
  inputs:
    command: custom
    workingDir: '$(Build.SourcesDirectory)'
    verbose: false
    customCommand: 'run ng build --prod'

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact: drop'
#   inputs:
#     PathtoPublish: dist