pool:
  name: Azure Pipelines
  demands: npm

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
    
- script: |
    npm install -g @angular/cli
    npm install
    npm run ng build --prod
  displayName: 'Install Angular CLI and Build'

- task: AzureStaticWebApp@0
  inputs:
    output_location: 'dist/browser'
    azure_static_web_apps_api_token: 'dbea67474895de1467757f4e9b1a377fe7b80e0e984cb00a4950b018a64aec3d4-70357e5b-46f8-4717-afa1-ca1a66d207d7010312099'